const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('main.db');
const Ctracks = require('./CtracksC.json')

db.serialize(() => {
    db.run(`CREATE TABLE IF NOT EXISTS communitytracks (
            guid TEXT UNIQUE,
            root TEXT,
            prefs TEXT,
            allow_copy BOOLEAN,
            base_assets_enabled BOOLEAN,
            exclusive_by_platform TEXT,
            is_race_allowed BOOLEAN,
            is_public BOOLEAN,
            is_public_for_drlpilots BOOLEAN,
            is_drl_official BOOLEAN,
            is_featured BOOLEAN,
            is_multigp BOOLEAN,
            is_tryouts BOOLEAN,
            is_virtual_season BOOLEAN,
            map_category TEXT,
            map_difficulty INT,
            map_distance FLOAT,
            map_dirty BOOLEAN,
            map_lighting INT,
            map_laps INT,
            map_stats_triangle_count INT,
            map_stats_object_count INT,
            map_asset_layers TEXT,
            map_styles TEXT,
            categories TEXT,
            prefs_auto_save BOOLEAN,
            rating_count INT,
            score INT,
            track_id TEXT,
            xp_value INT,
            xp_min_time INT,
            cm_collectable_count INT,
            collaborators TEXT,
            map_mode_type TEXT,
            map_id TEXT,
            map_title TEXT,
            steam_id TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME,
            version INT,
            title_translations TEXT,
            images TEXT,
            map_thumb TEXT,
            avatar TEXT,
            player_id TEXT,
            profile_name TEXT,
            profile_thumb TEXT,
            profile_color TEXT,
            profile_platform TEXT,
            profile_platform_id TEXT,
            flag_url TEXT,
            is_avatar_blocked BOOLEAN,
            full_track_url TEXT
            );`);
});


for (let i = 0; i < Ctracks.length; i++) {
    const track = Ctracks[i];
    const stmt = db.prepare(
        `INSERT INTO communitytracks (
            guid,
            root,
            prefs,
            allow_copy,
            base_assets_enabled,
            exclusive_by_platform,
            is_race_allowed,
            is_public,
            is_public_for_drlpilots,
            is_drl_official,
            is_featured,
            is_multigp,
            is_tryouts,
            is_virtual_season,
            map_category,
            map_difficulty,
            map_distance,
            map_dirty,
            map_lighting,
            map_laps,
            map_stats_triangle_count,
            map_stats_object_count,
            map_asset_layers,
            map_styles,
            categories,
            prefs_auto_save,
            rating_count,
            score,
            track_id,
            xp_value,
            xp_min_time,
            cm_collectable_count,
            collaborators,
            map_mode_type,
            map_id,
            map_title,
            steam_id,
            created_at,
            updated_at,
            version,
            title_translations,
            images,
            map_thumb,
            avatar,
            player_id,
            profile_name,
            profile_thumb,
            profile_color,
            profile_platform,
            profile_platform_id,
            flag_url,
            is_avatar_blocked,
            full_track_url
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(guid) DO NOTHING;`
    );

    stmt.run(
        track.guid,
        JSON.stringify(track.root),
        track.prefs,
        track["allow-copy"],
        track["base-assets-enabled"],
        JSON.stringify(track["exclusive-by-platform"]),
        track["is-race-allowed"],
        track["is-public"],
        track["is-public-for-drlpilots"],
        track["is-drl-official"],
        track["is-featured"],
        track["is-multigp"],
        track["is-tryouts"],
        track["is-virtual-season"],
        track["map-category"],
        track["map-difficulty"],
        track["map-distance"],
        track["map-dirty"],
        track["map-lighting"],
        track["map-laps"],
        track["map-stats-triangle-count"],
        track["map-stats-object-count"],
        JSON.stringify(track["map-asset-layers"]),
        JSON.stringify(track["map-styles"]),
        JSON.stringify(track["categories"]),
        track["prefs-auto-save"],
        track["rating-count"],
        track["score"],
        track["track-id"],
        track["xp-value"],
        track["xp-min-time"],
        track["cm-collectable-count"],
        JSON.stringify(track["collaborators"]),
        track["map-mode-type"],
        track["map-id"],
        track["map-title"],
        track["steam-id"],
        track["created-at"],
        track["updated-at"],
        track["version"],
        JSON.stringify(track["title-translations"]),
        JSON.stringify(track["images"]),
        track["map-thumb"],
        track["avatar"],
        track["player-id"],
        track["profile-name"],
        track["profile-thumb"],
        track["profile-color"],
        track["profile-platform"],
        track["profile-platform-id"],
        track["flag-url"],
        track["is-avatar-blocked"],
        track["full-track-url"]
    );

    console.log(`Inserted track ${i + 1}/${Ctracks.length}: ${track.guid}`);
}